default_language_version:
    python: python3.11
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      # Lint rules suggested by ruff docs, just for starters:
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml
    - id: mixed-line-ending
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
      # I like to run in strict mode usually but we can only do it after we have
      # type annotations consistently everywhere. We should later add:
      #args: [--strict, --ignore-missing-imports]
      # second is default that needs to be reproduced with explicitly given args
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: markdownlint
      files: "content/"
